## 드라이브 마운트

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

:

In [ ]:
#폴더로 이동
%cd /content/drive/MyDrive/DL project/

:

## 모듈 & 데이터 임포트

In [ ]:
import pandas as pd
import numpy as np
import warnings
import random
warnings.filterwarnings("ignore")

In [ ]:
from sklearn.covariance import EllipticEnvelope
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import classification_report

In [ ]:
train = pd.read_csv('train.csv')
val = pd.read_csv('val.csv')
test = pd.read_csv('test.csv')

In [ ]:
train_df = train.drop(columns=['ID'])
val_df = val.drop(columns=['ID'])

train_all = train_df
val_all = val_df.drop(columns=['Class'])
val_y = val_df['Class']
test_vari = test.drop(columns=['ID'])

In [ ]:
from sklearn.preprocessing import StandardScaler  # 표준화 
std = StandardScaler()

train_std = std.fit_transform(train_all) 
val_std = std.fit_transform(val_all) 
test_std = std.fit_transform(test_vari)

In [ ]:
# 레이블 변경 함수
def get_pred_label(model_pred):
  model_pred = np.where(model_pred==1, 0, model_pred)
  model_pred = np.where(model_pred==-1, 1, model_pred)
  return model_pred

In [ ]:
EE_model = EllipticEnvelope(support_fraction = 0.999, contamination = 0.00112, random_state = 42)
EE_model.fit(train_std)

In [ ]:
test_EE_pred = EE_model.predict(test_vari)
test_EE_pred1 = get_pred_label(test_EE_pred)

In [ ]:
submission = pd.read_csv('sample_submission.csv')
submission.head()

        ID  Class
0  AAAA0x1      1
1  AAAA0x2      1
2  AAAA0x5      1
3  AAAA0x7      1
4  AAAA0xc      1

In [ ]:
# 테스트 데이터 레이블 입력
submission['Class'] = test_EE_pred1

submission

             ID  Class
0       AAAA0x1      0
1       AAAA0x2      0
2       AAAA0x5      0
3       AAAA0x7      0
4       AAAA0xc      0
...         ...    ...
142498  0x4587f      0
142499  0x45880      0
142500  0x45884      0
142501  0x45885      0
142502  0x45887      0

[142503 rows x 2 columns]

In [ ]:
submission.to_csv('submission.csv',index=False)